name: NotCombatLogX
version: 2.4 Beta
description: 'CombatLogX Addon for stuff that isn''t really ''combat'''
author: SirBlobman
website: http://sirblobman.ddns.net
main: com.SirBlobman.combatlog.Not
database: false
depend: [CombatLogX]