name: CombatLogX
version: 1.0.1 Release
description: Prevent players from logging out during PvP
author: SirBlobman
website: http://sirblobman.ddns.net
main: com.SirBlobman.combatlog.CombatLog
database: false
depend: []
softdepend: [TitleManager, WorldGuard, LegacyFactions, FactionsUUID, Factions, Towny, PlotSquared]
commands:
  clreload:
    description: Reload the Config and Messages for this plugin
    usage: /clreload
    aliases: [ctreload, clr]
    permission: combatlog.reload
    permission-message: Ask an admin to reload the config!
  combattime:
    description: Check how much combat time you have left!
    usage: /combattime
    aliases: [ct, cl]