name: CombatLog
version: 0.0.22
description: Make sure players don't log out during PvP
author: SirBlobman
website: http://sirblobman.ddns.net
main: com.SirBlobman.combat_log.CombatLog
database: false
depend: []
commands:
  cl:
    description: Check how much time you have left in combat
    usage: /cl
    aliases: [combatlog, combattag, ct]