name: CombatLogX
version: 7.0.0.3
description: A simple combat-tagging plugin with many features
author: SirBlobman
main: com.SirBlobman.combatlogx.CombatLogX
database: false
depend: []
softdepend: [Citizens]
commands:
  combatlogx:
    description: Reload the Config and Messages for this plugin
    usage: /<command> <reload / tag / untag>
    aliases: [clx]
  combattime:
    description: Check how much combat time you have left.
    permission: combatlogx.time
    permission-message: You don''t have permission to check how much time you have left
    usage: /<command>
    aliases: [ct, cl]
permissions:
  combatlogx.*:
    description: Gives access to all CombatLogX perms (except bypass)
    default: op
    children:
      combatlogx.reload: true
      combatlogx.time: true
      combatlogx.untag: true
      combatlogx.tag: true
  combatlogx.reload:
    description: Allows you to reload the config
    default: op
  combatlogx.tag:
    description: Allows you to force someone into combat
    default: op
  combatlogx.untag:
    description: Allows you to force someone out of combat
    default: op
  combatlogx.time:
    description: Gives permission to check how much time you have left during combat
    default: true