name: CombatLogX
version: 4.0.0 Release
description: A simple combat-tagging plugin with many features
author: SirBlobman
main: com.SirBlobman.combatlogx.CombatLogX
database: false
depend: []
softdepend: [Factions, FactionsUUID, LegacyFactions, PlaceholderAPI, TitleManager, Towny, WorldGuard]
commands:
  clreload:
    description: Reload the Config and Messages for this plugin
    usage: /clreload
    aliases: [ctreload, clr]
    permission: combatlogx.reload
    permission-message: Ask an admin to reload the config.
  combattime:
    description: Check how much combat time you have left.
    usage: /combattime
    aliases: [ct, cl]