name: CombatLogX
version: ${combatlogx.version}
main: com.SirBlobman.combatlogx.CombatLogX

author: SirBlobman
description: An expandable combat-tagging plugin with actual logging options
api-version: 1.13

softdepend:
- Citizens
- Factions
- LegacyFactions
- Lands
- Parties
- PlaceholderAPI
- MVdWPlaceholderAPI
- Residence
- Towny
- WorldGuard
- BossBarAPI
- FeatherBoard

commands:
  combatlogx:
    usage: |-
        /<command> reload OR
        /<command> tag <player> OR
        /<command> untag <player> OR
        /<command> toggle <scoreboard/bossbar/actionbar>
    description: "Main command for CombatLogX"
    aliases: [combattag, combatlog, clx, ctx]

  combattime:
    usage: /<command> [player]
    description: Check how much time you or [player] has left in combat.
    aliases: [ct]